=== yimingf/dm2517/lab-dtd/start.dtd
<!ENTITY nbsp   "&#160;"> 
<!ENTITY Auml   "&#196;"> 
<!ENTITY Ouml   "&#214;"> 
<!ENTITY Uuml   "&#220;"> 
<!ENTITY auml   "&#228;"> 
<!ENTITY ouml   "&#246;"> 
<!ENTITY uuml   "&#252;"> 
<!ENTITY szlig   "&#223;">
<!ENTITY brkbar   "&#166;">
<!ENTITY Ccedil   "&#199;">
<!ENTITY ccedil   "&#231;">
<!ENTITY Aring    "&#197;">
<!ENTITY aring    "&#229;">
<!ENTITY % dish "food*, drink*">
<!ENTITY % person "firstname, lastname">

<!ELEMENT party (title, date, starttime, endtime?, arranger, location, price?, OSAdate?, description?, contact?, host*, toastmaster*, menu, guestlist)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT starttime (#PCDATA)>
<!ELEMENT endtime (#PCDATA)>
<!ELEMENT arranger (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price unit CDATA #IMPLIED>
<!ELEMENT OSAdate (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT contact (%person;, phone, email)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT host (%person;)>
<!ELEMENT toastmaster (%person;)>

<!ELEMENT menu (starter?, main_course, dessert?)>
<!ELEMENT starter (%dish;)>
<!ELEMENT main_course (%dish;)>
<!ELEMENT dessert (%dish;)>
<!ELEMENT food (#PCDATA)>
<!ATTLIST food type (shellfish|fish|meat|vegetarian|dairy|other) #IMPLIED>
<!ELEMENT drink (#PCDATA)>
<!ATTLIST drink type (beer|red_wine|white_wine|coffee|cognac|tea|punch|other) #IMPLIED>

<!ELEMENT guestlist (guest*)>
<!ELEMENT guest (%person;, affiliation, placementpreferences, foodrestrictions?, drinkrestrictions?)>
<!ATTLIST guest id ID #REQUIRED>
<!ATTLIST guest sex (male|female|unknown) #REQUIRED>
<!ELEMENT affiliation (#PCDATA)>
<!ELEMENT id EMPTY>
<!ATTLIST id nextto (yes|no) #REQUIRED>
<!ATTLIST id id IDREF #REQUIRED>
<!ELEMENT placementpreferences (id+)>
<!ELEMENT foodrestrictions (ingredient+)>
<!ELEMENT ingredient (#PCDATA)>
<!ELEMENT drinkrestrictions (drink+)>

=== yimingf/dm2517/lab-dtd/start.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE party SYSTEM "http://xml.csc.kth.se/~yimingf/DM2517/lab-dtd/start.dtd">
<party>
  <title>Amphiox Gasque</title>
  <date>2001-09-08</date>
  <starttime>18:00:00</starttime>

  <endtime>03:00:00</endtime>
  <arranger>MF</arranger>
  <location>MF</location>
  <price unit="sek">195</price>

  <OSAdate>2001-08-24</OSAdate>
  <description>
    Party for the new students at Medicinska F&ouml;reningen.
  </description>
  <contact>
    <firstname>Berra</firstname>

    <lastname>Berrasson</lastname>
    <phone>08-123456</phone>
    <email>berra@mf.ki.se</email>
  </contact>

  <host>
    <firstname>Anna</firstname>
    <lastname>Jerresand-&Ouml;hrstr&ouml;m</lastname>
  </host>

  <toastmaster>
    <firstname>Miranda</firstname>
    <lastname>Michanek</lastname>
  </toastmaster>
  <toastmaster>

    <firstname>Johannes</firstname>
    <lastname>Linde</lastname>
  </toastmaster>
  <menu>
    <starter>
      <food type="shellfish">Toast Skagen</food>
      <drink type="beer">Carlsberg Hof</drink>
    </starter>

    <main_course>
      <food type="meat">B&brkbar;uf Ni&ccedil;osie</food>
      <drink type="red_wine">Castillo de Benizar</drink>
    </main_course>

    <dessert>
      <food type="dairy">Vanilla icecream</food>
      <drink type="coffee">Espresso</drink>
      <drink type="cognac">Napoleon Cognac</drink>

    </dessert>
  </menu>
    <guestlist>
    <guest id="pnr771212-1212" sex="male">
      <firstname>Sven</firstname>
      <lastname>Svensson</lastname>

      <affiliation>KTH</affiliation>
      <placementpreferences>
        <id nextto="yes" id="pnr760101-0101" />
      </placementpreferences>
      <foodrestrictions>

        <ingredient>garlic</ingredient>
        <ingredient>meat</ingredient>
      </foodrestrictions>
      <drinkrestrictions>
        <drink type="red_wine" />

        <drink type="beer" />
      </drinkrestrictions>
    </guest>
    <guest id="pnr760101-0101" sex="female">
      <firstname>Anna</firstname>

      <lastname>Karlsson</lastname>
      <affiliation>MF</affiliation>
      <placementpreferences>
        <id nextto="no"  id="pnr771212-1212" />
      </placementpreferences>

      <drinkrestrictions>
        <drink type="beer" />
      </drinkrestrictions>
    </guest>
  </guestlist>
</party>
